<?php

namespace Database\Seeders;

use App\Modules\Marketplace\Domain\Models\Product;
use App\Modules\Marketplace\Domain\Models\Store;
use App\Modules\Marketplace\Domain\Models\StoreCatalog;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class MarketplaceProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            // ================= بذور زراعية =================
            [
                'store' => 'شركة الخير للمستلزمات والمبيدات الزراعية',
                'catalog' => 'بذور ومحاصيل بلدية',
                'category' => 'بذور زراعية',
                'name' => 'بذور ذرة بيضاء يمنية بلدية (محسنة)',
                'description' => 'بذور ذرة رفيعة بيضاء بلدية ممتازة، تم تنقيتها ومعالجتها ضد التفحم. ملائمة جداً لمناطق قاع جهران وصنعاء وسهل تهامة في الموسم الصيفي.',
                'price' => 7500,
                'unit' => 'كيس',
                'stock_quantity' => 150,
                'is_featured' => true,
                'image_url' => 'https://images.unsplash.com/photo-1551727974-8af20a3322f1?auto=format&fit=crop&w=600&q=80',
                'file_name' => 'products/white_corn_seeds.jpg',
            ],
            [
                'store' => 'مركز جهران للتقاوي والأسمدة المحسنة',
                'catalog' => 'تقاوي بطاطس وحبوب',
                'category' => 'بذور زراعية',
                'name' => 'بذور قمح بلدي ذماري (أصيل عالي الغلة)',
                'description' => 'تقاوي قمح بلدي صلب عالي الجودة والبروتين، متأقلم مع مناخ المرتفعات اليمنية ومقاوم للجفاف وأمراض الصدأ.',
                'price' => 18000,
                'unit' => 'كيس',
                'stock_quantity' => 85,
                'is_featured' => true,
                'image_url' => 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=600&q=80',
                'file_name' => 'products/wheat_seeds.jpg',
            ],
            [
                'store' => 'مركز جهران للتقاوي والأسمدة المحسنة',
                'catalog' => 'تقاوي بطاطس وحبوب',
                'category' => 'بذور زراعية',
                'name' => 'تقاوي بطاطس ديامنت ممتازة (رتبة أولى)',
                'description' => 'تقاوي بطاطس صنف ديامنت الهولندي المعتمد في اليمن، خالية من الفيروسات ومرض اللفحة، ذات إنتاجية ثمرية وفيرة وأحجام منتظمة.',
                'price' => 35000,
                'unit' => 'كيس',
                'stock_quantity' => 60,
                'is_featured' => true,
                'image_url' => 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=600&q=80',
                'file_name' => 'products/potato_seeds.jpg',
            ],
            [
                'store' => 'مؤسسة تهامة الزراعية والبيوت المحمية',
                'catalog' => 'بذور الخضروات الهجينة',
                'category' => 'بذور زراعية',
                'name' => 'بذور طماطم هجين F1 (مقاومة للفيروسات)',
                'description' => 'بذور طماطم هجينة غير محدودة النمو للبيوت المحمية والحقول المكشوفة. ثمار صلبة ممتازة للتسويق والنقل وذات لون أحمر جذاب.',
                'price' => 14000,
                'unit' => 'علبة',
                'stock_quantity' => 110,
                'is_featured' => true,
                'image_url' => 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=600&q=80',
                'file_name' => 'products/tomato_seeds.jpg',
            ],
            [
                'store' => 'مؤسسة تهامة الزراعية والبيوت المحمية',
                'catalog' => 'بذور الخضروات الهجينة',
                'category' => 'بذور زراعية',
                'name' => 'بذور بصل يمني أحمر تهامي',
                'description' => 'بذور بصل محلي نقي ذو قدرة تخزينية استثنائية وطعم حار وقوي، يحظى بطلب واسع في الأسواق المحلية وأسواق التصدير.',
                'price' => 9500,
                'unit' => 'كيلوجرام',
                'stock_quantity' => 95,
                'is_featured' => false,
                'image_url' => 'https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?auto=format&fit=crop&w=600&q=80',
                'file_name' => 'products/onion_seeds.jpg',
            ],
            [
                'store' => 'شركة الخير للمستلزمات والمبيدات الزراعية',
                'catalog' => 'بذور ومحاصيل بلدية',
                'category' => 'بذور زراعية',
                'name' => 'بذور دخن بلدي أبيض نقي',
                'description' => 'بذور دخن يمني بلدي يتميز بتحمله العالي للجفاف والحرارة، ومناسب جداً للزراعة المطرية في سهول تهامة وأبين ولحج.',
                'price' => 6000,
                'unit' => 'كيس',
                'stock_quantity' => 70,
                'is_featured' => false,
                'image_url' => 'https://images.unsplash.com/photo-1596489823521-707db99d2595?auto=format&fit=crop&w=600&q=80',
                'file_name' => 'products/millet_seeds.jpg',
            ],

            // ================= أسمدة ومخصبات =================
            [
                'store' => 'شركة الخير للمستلزمات والمبيدات الزراعية',
                'catalog' => 'أسمدة ومخصبات تربة',
                'category' => 'أسمدة',
                'name' => 'سماد مركب NPK متوازن (20-20-20) عالي الذوبان',
                'description' => 'سماد بودرة سريع الذوبان 100% يحتوي على العناصر الكبرى (نيتروجين، فوسفور، بوتاسيوم) بنسب متوازنة مدعمة بالعناصر الصغرى لجميع مراحل النمو.',
                'price' => 22000,
                'unit' => 'كيس',
                'stock_quantity' => 120,
                'is_featured' => true,
                'image_url' => 'https://images.unsplash.com/photo-1585314062340-f1a5a7c9328d?auto=format&fit=crop&w=600&q=80',
                'file_name' => 'products/npk_fertilizer.jpg',
            ],
            [
                'store' => 'شركة الخير للمستلزمات والمبيدات الزراعية',
                'catalog' => 'أسمدة ومخصبات تربة',
                'category' => 'أسمدة',
                'name' => 'يوريا زراعية نقية 46% نيتروجين',
                'description' => 'سماد نيتروجيني محبب عالي الكفاءة لتحفيز النمو الخضري القوي في محاصيل الحبوب والخضار وأشجار الفاكهة.',
                'price' => 17500,
                'unit' => 'كيس',
                'stock_quantity' => 200,
                'is_featured' => false,
                'image_url' => 'https://images.unsplash.com/photo-1628352081506-83c43123ed6d?auto=format&fit=crop&w=600&q=80',
                'file_name' => 'products/urea_fertilizer.jpg',
            ],
            [
                'store' => 'شركة الخير للمستلزمات والمبيدات الزراعية',
                'catalog' => 'أسمدة ومخصبات تربة',
                'category' => 'أسمدة',
                'name' => 'هيوميك وفولفيك أسيد عضوي مركز 85%',
                'description' => 'مخصب عضوي طبيعي لتحسين خواص التربة الكيميائية والفيزيائية، وزيادة قدرة الجذور على امتصاص العناصر الغذائية وتقليل الملوحة.',
                'price' => 11000,
                'unit' => 'عبوة',
                'stock_quantity' => 90,
                'is_featured' => true,
                'image_url' => 'https://images.unsplash.com/photo-1599818855423-e5d761e389d3?auto=format&fit=crop&w=600&q=80',
                'file_name' => 'products/humic_acid.jpg',
            ],
            [
                'store' => 'مركز جهران للتقاوي والأسمدة المحسنة',
                'catalog' => 'تقاوي بطاطس وحبوب',
                'category' => 'أسمدة',
                'name' => 'سلفات بوتاسيوم ذوابة للمحاصيل الثمرية',
                'description' => 'سماد بوتاسي عالي النقاوة مخصص لزيادة حجم الثمار وتحسين نسبة السكر واللون في العنب، الرمان، والبطاطس.',
                'price' => 28000,
                'unit' => 'كيس',
                'stock_quantity' => 75,
                'is_featured' => false,
                'image_url' => 'https://images.unsplash.com/photo-1563245372-f21724e3856d?auto=format&fit=crop&w=600&q=80',
                'file_name' => 'products/potassium_sulfate.jpg',
            ],
            [
                'store' => 'مشاتل سحول إب الخضراء',
                'catalog' => 'شتلات البن اليمني',
                'category' => 'أسمدة',
                'name' => 'شيلات حديد EDDHA 6% لمعالجة اصفرار الأوراق',
                'description' => 'حديد مخلبي فعال حتى في الأراضي القلوية والكلسية الشائعة في اليمن، يعالج ظاهرة الاصفرار الوردي ويعيد النضارة للأشجار والخضار.',
                'price' => 8500,
                'unit' => 'عبوة',
                'stock_quantity' => 130,
                'is_featured' => false,
                'image_url' => 'https://images.unsplash.com/photo-1530595467537-0b5996c41f2d?auto=format&fit=crop&w=600&q=80',
                'file_name' => 'products/iron_chelate.jpg',
            ],

            // ================= مبيدات زراعية =================
            [
                'store' => 'شركة الخير للمستلزمات والمبيدات الزراعية',
                'catalog' => 'مبيدات ووقاية نباتية',
                'category' => 'مبيدات زراعية',
                'name' => 'مبيد فطري جهازي واسع الطيف (مانكوزيب 80%)',
                'description' => 'مبيد فطري ذو تأثير وقائي وعلاجي قوي لمكافحة البياض الدقيقي والزغبي واللفحة المبكرة والمتأخرة في البطاطس والطماطم.',
                'price' => 6500,
                'unit' => 'عبوة',
                'stock_quantity' => 140,
                'is_featured' => true,
                'image_url' => 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=600&q=80',
                'file_name' => 'products/fungicide_mancozeb.jpg',
            ],
            [
                'store' => 'شركة الخير للمستلزمات والمبيدات الزراعية',
                'catalog' => 'مبيدات ووقاية نباتية',
                'category' => 'مبيدات زراعية',
                'name' => 'مبيد حشري فعال لمكافحة الذبابة البيضاء والمن',
                'description' => 'مبيد جهازي حديث سريع الامتصاص، يقضي بفاعلية على حشرات المن، الجاسيد، والذبابة البيضاء الناقلة للفيروسات النباتية.',
                'price' => 7800,
                'unit' => 'لتر',
                'stock_quantity' => 80,
                'is_featured' => false,
                'image_url' => 'https://images.unsplash.com/photo-1590682680695-43b964a3ae17?auto=format&fit=crop&w=600&q=80',
                'file_name' => 'products/insecticide_aphids.jpg',
            ],
            [
                'store' => 'مستودعات صعدة للمعدات ومضخات الآبار',
                'catalog' => 'معدات وآلات الحقل',
                'category' => 'مبيدات زراعية',
                'name' => 'كبريت ميكروني زراعي قابل للبلل 80%',
                'description' => 'مبيد وقائي فطري وعنكبوكي نقي، يمنع انتشار البياض الدقيقي وحلم الغبار في حقول العنب وأشجار الرمان والطماطم.',
                'price' => 12000,
                'unit' => 'كيس',
                'stock_quantity' => 95,
                'is_featured' => false,
                'image_url' => 'https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?auto=format&fit=crop&w=600&q=80',
                'file_name' => 'products/sulfur_powder.jpg',
            ],

            // ================= أنظمة ري وطاقة =================
            [
                'store' => 'مؤسسة البركة لأنظمة الطاقة والري الحديث',
                'catalog' => 'منظومات الطاقة الشمسية للآبار',
                'category' => 'أنظمة ري وطاقة',
                'name' => 'غطاس مياه طاقة شمسية 10 حصان للآبار الارتوازية',
                'description' => 'مضخة غاطسة ستانلس ستيل إيطالية التصميم للمياه العميقة حتى 180 متراً، تعمل بكفاءة عالية على منظومة الألواح الشمسية دون الحاجة للديزل.',
                'price' => 480000,
                'unit' => 'حبة',
                'stock_quantity' => 15,
                'is_featured' => true,
                'image_url' => 'https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?auto=format&fit=crop&w=600&q=80',
                'file_name' => 'products/submersible_pump.jpg',
            ],
            [
                'store' => 'مؤسسة البركة لأنظمة الطاقة والري الحديث',
                'catalog' => 'منظومات الطاقة الشمسية للآبار',
                'category' => 'أنظمة ري وطاقة',
                'name' => 'إينفرتر طاقة شمسية زراعي 15 كيلوواط VFD',
                'description' => 'محول تردد ذكي متخصص لمضخات الآبار الزراعية يدعم التشغيل بالطاقة الشمسية مع تحكم أوتوماتيكي بسرعة الضخ وحماية من الجفاف.',
                'price' => 320000,
                'unit' => 'حبة',
                'stock_quantity' => 20,
                'is_featured' => true,
                'image_url' => 'https://images.unsplash.com/photo-1509391365360-2e959784a276?auto=format&fit=crop&w=600&q=80',
                'file_name' => 'products/solar_inverter.jpg',
            ],
            [
                'store' => 'مؤسسة البركة لأنظمة الطاقة والري الحديث',
                'catalog' => 'شبكات وليات الري بالتنقيط',
                'category' => 'أنظمة ري وطاقة',
                'name' => 'لفة ليات ري بالتنقيط GR (400 متر - نقاطات مدمجة)',
                'description' => 'أنبوب ري بالتنقيط عالي الجودة مقاوم لأشعة الشمس فوق البنفسجية والانسداد، مسافة النقاطات 40 سم بتدفق 4 لتر/ساعة للمزارع والبيوت المحمية.',
                'price' => 26000,
                'unit' => 'لفة',
                'stock_quantity' => 110,
                'is_featured' => true,
                'image_url' => 'https://images.unsplash.com/photo-1527842891421-42eec6e703ea?auto=format&fit=crop&w=600&q=80',
                'file_name' => 'products/drip_pipe.jpg',
            ],
            [
                'store' => 'مؤسسة البركة لأنظمة الطاقة والري الحديث',
                'catalog' => 'شبكات وليات الري بالتنقيط',
                'category' => 'أنظمة ري وطاقة',
                'name' => 'محبس ري أوتوماتيكي ذكي (Solonoid Valve 2 Inch)',
                'description' => 'صمام ري كهربائي متوافق مع وحدات التحكم الذكية (IoT)، يتحمل ضغط مائي حتى 10 بار ويوفر في استهلاك المياه بدقة فائقة.',
                'price' => 38000,
                'unit' => 'حبة',
                'stock_quantity' => 45,
                'is_featured' => false,
                'image_url' => 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=600&q=80',
                'file_name' => 'products/smart_valve.jpg',
            ],
            [
                'store' => 'مؤسسة البركة لأنظمة الطاقة والري الحديث',
                'catalog' => 'شبكات وليات الري بالتنقيط',
                'category' => 'أنظمة ري وطاقة',
                'name' => 'فلتر تنقية مياه شبكي مركزي لأنظمة الري (3 إنش)',
                'description' => 'فلتر شبكي ستانلس ستيل يزيل الشوائب والرمال من مياه الآبار لحماية النقاطات من الانسداد وإطالة عمر شبكة الري.',
                'price' => 45000,
                'unit' => 'حبة',
                'stock_quantity' => 30,
                'is_featured' => false,
                'image_url' => 'https://images.unsplash.com/photo-1584467735871-8e85353a8413?auto=format&fit=crop&w=600&q=80',
                'file_name' => 'products/water_filter.jpg',
            ],

            // ================= مشاتل =================
            [
                'store' => 'مشاتل سحول إب الخضراء',
                'catalog' => 'شتلات البن اليمني',
                'category' => 'مشاتل',
                'name' => 'شتلات بن يمني أصيل (عديني معتمد)',
                'description' => 'شتلات بن عمر سنة ونصف مرباة في أكياس زراعية من أمهات نقية في جبال حراز وبني مطر، جاهزة للغرس الميداني المباشر.',
                'price' => 2500,
                'unit' => 'حبة',
                'stock_quantity' => 350,
                'is_featured' => true,
                'image_url' => 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=600&q=80',
                'file_name' => 'products/coffee_sapling.jpg',
            ],
            [
                'store' => 'مشاتل سحول إب الخضراء',
                'catalog' => 'أشجار الفواكه والحمضيات',
                'category' => 'مشاتل',
                'name' => 'شتلات رمان صعداوي أحمر مطعم',
                'description' => 'شتلات رمان صعداوي أصلي ذو حبات داكنة وسكرية عالية، خالية من الأمراض وسريعة الدخول في طور الإثمار التجاري.',
                'price' => 3000,
                'unit' => 'حبة',
                'stock_quantity' => 200,
                'is_featured' => true,
                'image_url' => 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=600&q=80',
                'file_name' => 'products/pomegranate_sapling.jpg',
            ],
            [
                'store' => 'مشاتل سحول إب الخضراء',
                'catalog' => 'أشجار الفواكه والحمضيات',
                'category' => 'مشاتل',
                'name' => 'شتلات مانجو تيمي مصري مطعم ممتاز',
                'description' => 'شتلات مانجو مطعمة ممتازة لسهل تهامة ولحج وأبين، ثمار كبيرة قليلة الألياف وحلوة المذاق ذات مردود اقتصادي رائع.',
                'price' => 4500,
                'unit' => 'حبة',
                'stock_quantity' => 150,
                'is_featured' => false,
                'image_url' => 'https://images.unsplash.com/photo-1553279768-865429fa0078?auto=format&fit=crop&w=600&q=80',
                'file_name' => 'products/mango_sapling.jpg',
            ],
            [
                'store' => 'مشاتل سحول إب الخضراء',
                'catalog' => 'أشجار الفواكه والحمضيات',
                'category' => 'مشاتل',
                'name' => 'عقل وشتلات عنب رازقي وعاصمي سكرية',
                'description' => 'شتلات عنب منتقاة من أشهر كروم بني حشيش وصنعاء، صنف رازقي أبيض شفاف وعاصمي أحمر غزير العناقيد.',
                'price' => 2200,
                'unit' => 'حبة',
                'stock_quantity' => 280,
                'is_featured' => false,
                'image_url' => 'https://images.unsplash.com/photo-1537640538966-79f369143f8f?auto=format&fit=crop&w=600&q=80',
                'file_name' => 'products/grape_sapling.jpg',
            ],

            // ================= معدات وأدوات =================
            [
                'store' => 'مستودعات صعدة للمعدات ومضخات الآبار',
                'catalog' => 'معدات وآلات الحقل',
                'category' => 'معدات وأدوات',
                'name' => 'رشاشة مبيدات ظهرية بطارية قابلة للشحن (20 لتر)',
                'description' => 'مرشة كهربائية ظهرية بمضخة قوية وضغط عالي قابل للتعديل، بطارية ليثيوم تدوم 6 ساعات عمل متواصلة مع فوهات رش متعددة.',
                'price' => 29000,
                'unit' => 'حبة',
                'stock_quantity' => 45,
                'is_featured' => true,
                'image_url' => 'https://images.unsplash.com/photo-1590682680695-43b964a3ae17?auto=format&fit=crop&w=600&q=80',
                'file_name' => 'products/battery_sprayer.jpg',
            ],
            [
                'store' => 'مستودعات صعدة للمعدات ومضخات الآبار',
                'catalog' => 'معدات وآلات الحقل',
                'category' => 'معدات وأدوات',
                'name' => 'عزاقة ومحراث يدوي بنزين 7 حصان لتقليب التربة',
                'description' => 'عزاقة حقلية خفيفة وعملية بعرض حراثة 80 سم وعمق يصل إلى 30 سم، مثالية للأحواض والمدرجات الجبلية وبساتين الفاكهة.',
                'price' => 195000,
                'unit' => 'حبة',
                'stock_quantity' => 12,
                'is_featured' => true,
                'image_url' => 'https://images.unsplash.com/photo-1581092335397-9583fe92d232?auto=format&fit=crop&w=600&q=80',
                'file_name' => 'products/field_tiller.jpg',
            ],
            [
                'store' => 'مستودعات صعدة للمعدات ومضخات الآبار',
                'catalog' => 'معدات وآلات الحقل',
                'category' => 'معدات وأدوات',
                'name' => 'مقص تقليم أشجار هيدروليكي فائق الحدة',
                'description' => 'مقص تقليم احترافي بشفرات فولاذية يابانية SK5 يقطع الأغصان بسلاسة حتى قطر 30 ملم دون إتلاف لحاء الشجرة.',
                'price' => 8500,
                'unit' => 'حبة',
                'stock_quantity' => 60,
                'is_featured' => false,
                'image_url' => 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?auto=format&fit=crop&w=600&q=80',
                'file_name' => 'products/pruning_shears.jpg',
            ],
            [
                'store' => 'مستودعات صعدة للمعدات ومضخات الآبار',
                'catalog' => 'معدات وآلات الحقل',
                'category' => 'معدات وأدوات',
                'name' => 'جهاز قياس رطوبة وحموضة التربة الرقمي 4 في 1',
                'description' => 'مقياس إلكتروني يقيس رطوبة التربة، درجة الحموضة (pH)، درجة الحرارة، وشدة الضوء، لا غنى عنه للمزارع الذكي لضبط الري بدقة.',
                'price' => 15000,
                'unit' => 'حبة',
                'stock_quantity' => 35,
                'is_featured' => true,
                'image_url' => 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=600&q=80',
                'file_name' => 'products/soil_tester.jpg',
            ],

            // ================= منتجات زراعية طازجة =================
            [
                'store' => 'مزارع الصنعاني للبن والمنتجات العضوية',
                'catalog' => 'محاصيل البن المختص',
                'category' => 'منتجات زراعية',
                'name' => 'بن يمني خولاني فاخر مجفف طبيعياً (درجة أولى)',
                'description' => 'بن يمني نخب أول مقطوف يدوياً حبة حبة من مدرجات خولان الطيال ومجفف على أسرّة شمسية تقليدية، نكهات زهرية وفاكهية فريدة.',
                'price' => 16000,
                'unit' => 'كيلوجرام',
                'stock_quantity' => 50,
                'is_featured' => true,
                'image_url' => 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?auto=format&fit=crop&w=600&q=80',
                'file_name' => 'products/khawlani_coffee.jpg',
            ],
            [
                'store' => 'مزارع الصنعاني للبن والمنتجات العضوية',
                'catalog' => 'عسل ومنتجات طبيعية',
                'category' => 'منتجات زراعية',
                'name' => 'عسل سدر يمني دوعني ملكي طبيعي 100%',
                'description' => 'عسل سدر أصلي نقي مستخرج من وادي دوعن الشهير، غني بالإنزيمات ومضادات الأكسدة ومفحوص مخبرياً لضمان النقاء الكامل.',
                'price' => 45000,
                'unit' => 'كيلوجرام',
                'stock_quantity' => 25,
                'is_featured' => true,
                'image_url' => 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?auto=format&fit=crop&w=600&q=80',
                'file_name' => 'products/sidr_honey.jpg',
            ],
            [
                'store' => 'مزارع الصنعاني للبن والمنتجات العضوية',
                'catalog' => 'عسل ومنتجات طبيعية',
                'category' => 'منتجات زراعية',
                'name' => 'لوز خولاني يمني بلدي مقشر طازج',
                'description' => 'لوز جبلي بلدي حلو الطعم غني بالزيوت الطبيعية والدهون المفيدة، إنتاج حديث من بساتين بني مطر وخولان.',
                'price' => 18000,
                'unit' => 'كيلوجرام',
                'stock_quantity' => 40,
                'is_featured' => false,
                'image_url' => 'https://images.unsplash.com/photo-1508061252445-5350f3ab0a55?auto=format&fit=crop&w=600&q=80',
                'file_name' => 'products/yemeni_almonds.jpg',
            ],
            [
                'store' => 'مزارع الصنعاني للبن والمنتجات العضوية',
                'catalog' => 'محاصيل البن المختص',
                'category' => 'منتجات زراعية',
                'name' => 'زبيب رازقي ذهبي فاخر من كروم صنعاء',
                'description' => 'زبيب يمني رازقي مجفف شمسياً دون أي إضافات كيماوية، حجم حبة كبير ونسبة سكر عالية ومذاق لا يقاوم.',
                'price' => 12000,
                'unit' => 'كيلوجرام',
                'stock_quantity' => 65,
                'is_featured' => false,
                'image_url' => 'https://images.unsplash.com/photo-1568702846914-96b305d2aaeb?auto=format&fit=crop&w=600&q=80',
                'file_name' => 'products/raisins.jpg',
            ],
        ];

        foreach ($products as $p) {
            $store = Store::where('store_name', $p['store'])->first();
            if (! $store) {
                continue;
            }

            $catalog = StoreCatalog::where('store_id', $store->id)
                ->where('name', $p['catalog'])
                ->first();

            $imagePath = ImageHelper::download($p['image_url'], $p['file_name'], $p['name']);

            Product::create([
                'store_id' => $store->id,
                'catalog_id' => $catalog?->id,
                'category' => $p['category'],
                'name' => $p['name'],
                'slug' => Str::slug($p['name'], '-', 'ar') ?: 'product-'.Str::random(6),
                'description' => $p['description'],
                'price' => $p['price'],
                'unit' => $p['unit'],
                'stock_quantity' => $p['stock_quantity'],
                'is_featured' => $p['is_featured'],
                'image_url' => $imagePath,
                'payment_methods' => ['cash', 'bank_transfer', 'credit_card'],
            ]);
        }
    }
}
