<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Modules\PlantGuide\Domain\Models\CareGuide;
use App\Modules\PlantGuide\Domain\Models\CropGuide;
use App\Modules\PlantGuide\Domain\Models\Plant;
use Illuminate\Database\Seeder;

class YemeniPlantGuideSeeder extends Seeder
{
    public function run(): void
    {
        $categories = [
            'حبوب' => ['icon' => 'wheat', 'description' => 'محاصيل الحبوب الغذائية الاستراتيجية في اليمن كالغرب والذرة والقمح والدخن.'],
            'خضروات' => ['icon' => 'carrot', 'description' => 'الخضروات الحقلية والمحمية كالبطاطس والطماطم والبصل والخيار.'],
            'فواكه' => ['icon' => 'apple', 'description' => 'أشجار الفاكهة كالعنب والرمان والمانجو والتمور والموز.'],
            'محاصيل نقدية' => ['icon' => 'banknote', 'description' => 'المحاصيل الاقتصادية كالبن اليمني والسمسم والقطن.'],
            'أعشاب ونباتات طبية' => ['icon' => 'leaf', 'description' => 'الأعشاب الطبية والعطرية كالحلبة، الحبة السوداء، والنعناع.'],
        ];

        $categoryMap = [];
        foreach ($categories as $name => $data) {
            $cat = Category::updateOrCreate(
                ['name' => $name, 'type' => 'crop'],
                ['icon' => $data['icon'], 'description' => $data['description']]
            );
            $categoryMap[$name] = $cat->id;
        }

        $plants = [
            [
                'category' => 'حبوب',
                'common_name' => 'الذرة الرفيعة (الغرب)',
                'scientific_name' => 'Sorghum bicolor',
                'scientific_definition' => 'نبات حولي نجيلي يشكل المحصول الغذائي الأساسي في الريف اليمني، يزرع بكثافة في المرتفعات والسهول.',
                'description' => 'الذرة الرفيعة أهم محصول حبوب في اليمن، تتميز بمقاومتها للجفاف وتستخدم حبوبها لصنع الخبز البلدي (اللحوح والكبان)، وسيقانها كعلف ممتاز للماشية.',
                'planting_season' => 'أبريل - يوليو (موسم الصيف والمطر)',
                'harvest_time' => '110-130 يوم',
                'water_needs' => 'معتدل، تعتمد على مياه الأمطار والري السيلي التكميلي',
                'fertilizer_needs' => 'سماد بلدي متخمر قبل البذر ودفعة يوريا عند التسنبل',
                'benefits' => 'غنية بالألياف والمعادن والحديد، خالية من الجلوتين، مصدر رئيسي للأمن الغذائي الريفي.',
                'growth_guide' => 'تحرث الأرض جيداً ثم تبذر الحبوب على خطوط بمسافة 60 سم، وتجرى عملية الخف والعزيق عند عمر 20 يوماً.',
                'growing_conditions' => 'تحتاج شمس ساطعة ودرجة حرارة بين 24-32 مئوية، تتحمل الجفاف المؤقت.',
                'soil_and_ph' => 'تربة طينية طميية جيدة الصرف، درجة حموضة 6.0 - 7.5.',
                'uses' => 'إنتاج الحبوب، صناعة اللحوح والمخبوزات اليمنية، علف للثروة الحيوانية.',
                'pests_and_diseases' => 'دودة القصب، المن، مرض التفحم في الحبوب، وحفار الساق.',
                'harvesting_and_storage' => 'تحصد الرؤوس بعد جفاف الحبوب وتفرز في مخازن مهواة (المدفن التقليدي أو الصوامع).',
                'image_url' => 'https://images.unsplash.com/photo-1596489823521-707db99d2595?auto=format&fit=crop&w=800&q=80',
                'file_name' => 'plants/sorghum.jpg',
                'care' => [
                    'watering_schedule' => 'كل 10-14 يوماً عند انحباس المطر، خاصة في مرحلة الإزهار',
                    'sunlight_requirement' => 'شمس كاملة مباشرة (8-10 ساعات يومياً)',
                    'temperature' => '22 - 34 مئوية',
                    'humidity' => '30% - 50%',
                    'fertilizing_schedule' => 'دفعة أساس عند الحراثة ودفعة نيتروجين عند طول 30 سم',
                    'pruning_guide' => 'إزالة الخلفات الجانبية الضعيفة لتركيز الغذاء في الساق الرئيسية',
                ],
            ],
            [
                'category' => 'محاصيل نقدية',
                'common_name' => 'البن اليمني العربي (موكا)',
                'scientific_name' => 'Coffea arabica',
                'scientific_definition' => 'شجرة دائمة الخضرة من الفصيلة الفوية، موطن أجود سلالات البن في العالم المزروعة على المدرجات الجبلية العالية.',
                'description' => 'جوهرة الزراعة اليمنية وأشهر محصول تاريخي اشتهر عالمياً باسم Mocha Coffee. يزرع على ارتفاعات بين 1200 و2200 متر في مناخة، حراز، خولان، يافع، وبرع.',
                'planting_season' => 'مارس - مايو (بداية أمطار الربيع)',
                'harvest_time' => 'أكتوبر - ديسمبر (موسم الجني الشتوي)',
                'water_needs' => 'ري منتظم بالراحة أو التنقيط، تجنب تغريق الجذور',
                'fertilizer_needs' => 'سماد عضوي نباتي/حيواني مخمر مع بوتاسيوم طبيعي أثناء عقد الثمار',
                'benefits' => 'يتميز بنكهات فاكهية وشوكولاتية فريدة، مصدر فخر قومي وعائد اقتصادي مرتفع للمزارع.',
                'growth_guide' => 'تغرس الشتلات المعتمدة في جور عميقة مسمدة، وتحمى من الرياح القوية بإنشاء مصدات أو زراعة أشجار ظل خفيفة.',
                'growing_conditions' => 'مرتفعات جبلية بدرجات حرارة معتدلة 15-26 مئوية مع نسيم رطب وشمس غير حارقة.',
                'soil_and_ph' => 'تربة بركانية طميية غنية بالمعادن وذات صرف ممتاز، pH 5.5 - 6.5.',
                'uses' => 'تصدير حبوب القهوة المختصة، تحضير القشر اليمني التقليدي، مشروب البن المحلي.',
                'pests_and_diseases' => 'حفار ساق البن، صدأ الأوراق، وحشرة المن.',
                'harvesting_and_storage' => 'جني الثمار الحمراء الكرزية باليد حبة حبة، وتجفيفها على أسرّة خشبية شمسية بعيداً عن الرطوبة.',
                'image_url' => 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80',
                'file_name' => 'plants/yemeni_coffee.jpg',
                'care' => [
                    'watering_schedule' => 'كل 7-10 أيام شتاءً وكل 5-7 أيام صيفاً مع تصريف محكم',
                    'sunlight_requirement' => 'ضوء ساطع مفلتر أو ظل جزئي بنسبة 30%',
                    'temperature' => '16 - 25 مئوية',
                    'humidity' => '50% - 70%',
                    'fertilizing_schedule' => 'تسميد عضوي في الخريف وبوتاسيوم سائل كل شهرين أثناء الإثمار',
                    'pruning_guide' => 'تقليم الأفرع المتشابكة واليابسة بعد الجني لتجديد الأفرع الثمرية',
                ],
            ],
            [
                'category' => 'حبوب',
                'common_name' => 'القمح البلدي',
                'scientific_name' => 'Triticum aestivum',
                'scientific_definition' => 'محصول حبوب حولي شتوي رئيسي، يعتبر الغذاء الأساسي للخبز في الهضبة والوسط اليمني.',
                'description' => 'يزرع القمح في قاع جهران وذمار وصنعاء وعمران ومأرب. الحبوب البلدية صلبة وذات طعم استثنائي وقيمة غذائية تفوق المستورد.',
                'planting_season' => 'أكتوبر - نوفمبر (الموسم الخريفي/الشتوي)',
                'harvest_time' => '100-120 يوم (مارس - أبريل)',
                'water_needs' => 'ري كل 10-15 يوماً (يحتاج 4 إلى 6 ريات رئيسية)',
                'fertilizer_needs' => 'سوبر فوسفات عند الزراعة ويوريا على دفعتين',
                'benefits' => 'غني بالكربوهيدرات المعقدة والألياف، أساس إنتاج خبز البر والسبايا والفتة اليمنية.',
                'growth_guide' => 'حراثة التربة مرتين وتسويتها ثم نثر البذور أو بذرها بالسطارات بعمق 3-5 سم.',
                'growing_conditions' => 'جو بارد معتدل أثناء النمو وجاف دافئ أثناء النضج.',
                'soil_and_ph' => 'تربة صفراء أو طميية خصبة، pH 6.2 - 7.5.',
                'uses' => 'دقيق الخبز، المعجنات الشعبية، تبن القمح كعلف ممتاز للماشية.',
                'pests_and_diseases' => 'صدأ القمح الأصفر والأسود، التفحم السائب، والبياض الدقيقي.',
                'harvesting_and_storage' => 'الحصاد عند اصفرار النبات وجفاف الحبوب تحت رطوبة أقل من 12%.',
                'image_url' => 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&w=800&q=80',
                'file_name' => 'plants/wheat.jpg',
                'care' => [
                    'watering_schedule' => 'ريات حاسمة: رية المحاياة، رية التفريع، رية طرد السنابل، ورية امتلاء الحبوب',
                    'sunlight_requirement' => 'شمس كاملة مباشرة (8 ساعات يومياً)',
                    'temperature' => '12 - 24 مئوية',
                    'humidity' => '35% - 55%',
                    'fertilizing_schedule' => 'فوسفور أساسي ونيتروجين بعد 3 أسابيع من الإنبات',
                    'pruning_guide' => 'لا يتطلب تقليماً بل مكافحة مبكرة للحشائش المنافسة',
                ],
            ],
            [
                'category' => 'فواكه',
                'common_name' => 'الرمان الصعداوي',
                'scientific_name' => 'Punica granatum',
                'scientific_definition' => 'شجرة فاكهة معمرة نفضية تشتهر بها مزارع صعدة وعمران وذمار، وثمارها من الأكبر حجماً والأحلى مذاقاً في الشرق الأوسط.',
                'description' => 'رمان صعدة معروف بقشرته الحمراء اللامعة وبذوره العصيرية الحلوة قليلة الصلابة. يعد من أهم محاصيل التصدير إلى دول الخليج.',
                'planting_season' => 'فبراير - مارس (غرس العقل والشتلات)',
                'harvest_time' => 'أغسطس - أكتوبر',
                'water_needs' => 'ري منتظم ومتباعد، تقليل الري قبل النضج لتفادي تشقق الثمار',
                'fertilizer_needs' => 'سماد عضوي شتوي، وبوتاسيوم وكالسيوم صيفاً لصلابة القشرة',
                'benefits' => 'غني بمضادات الأكسدة القوية، يقلل الالتهابات ويدعم صحة القلب والشرايين.',
                'growth_guide' => 'تغرس الشتلات بمسافة 4×4 أمتار في أحواض مستقلة مجهزة بشبكة تنقيط.',
                'growing_conditions' => 'مناخ دافئ جاف صيفاً وبارد شتاءً لتلبية ساعات البرودة اللازمة لكسر السكون.',
                'soil_and_ph' => 'تربة طميية رملية عميقة وجيدة الصرف، pH 6.5 - 7.8.',
                'uses' => 'استهلاك طازج، عصائر طبيعية، دبس الرمان، وتصدير تجاري.',
                'pests_and_diseases' => 'دودة ثمار الرمان (فراشة الرمان)، المن، وحلم الغبار، وتشقق الثمار.',
                'harvesting_and_storage' => 'تقطف الثمار بالمقص مع جزء من العنق، وتخزن في حرارة 5 مئوية لعدة أشهر.',
                'image_url' => 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=800&q=80',
                'file_name' => 'plants/pomegranate.jpg',
                'care' => [
                    'watering_schedule' => 'كل 5-7 أيام صيفاً مع ثبات كمية المياه لمنع الانفجار الثمري',
                    'sunlight_requirement' => 'شمس ساطعة كاملة طوال النهار',
                    'temperature' => '18 - 35 مئوية',
                    'humidity' => '25% - 45%',
                    'fertilizing_schedule' => 'سماد بلدي متخمر في كانون الأول، ورش ورقي بالكالسيوم في الصيف',
                    'pruning_guide' => 'تقليم كأسي شتوي لإزالة السرطانات والسرطانات المائية وفتح قلب الشجرة للشمس',
                ],
            ],
            [
                'category' => 'فواكه',
                'common_name' => 'العنب الرازقي والعاصمي',
                'scientific_name' => 'Vitis vinifera',
                'scientific_definition' => 'شجيرة كرمة معمرة متسلقة، تعد مزارع بني حشيش والروضة وخولان في صنعاء مهد أجود أصنافها التاريخية.',
                'description' => 'يتميز العنب اليمني بأنواعه المتعددة (الرازقي الأبيض الشفاف، العاصمي الوردي، والأسود)، ويشتهر بحلاوته العالية وقيمته الفائقة في إنتاج الزبيب.',
                'planting_season' => 'يناير - فبراير (غرس العقل والشتلات)',
                'harvest_time' => 'يوليو - سبتمبر',
                'water_needs' => 'ري غزير في الربيع والصيف، ويتوقف تماماً قبل القطف بأسبوعين لتركيز السكر',
                'fertilizer_needs' => 'سماد متوازن وبوتاسيوم عالي عند تحول لون الحبات',
                'benefits' => 'منجم للطاقة الطبيعية والسكريات الصحية ومضادات الشيخوخة.',
                'growth_guide' => 'يربى على تعريشات أو دعامات خشبية ومعدنية بارتفاع مترين للسماح بتهوية العناقيد.',
                'growing_conditions' => 'جو جاف مشمس مع هواء عليل، وأمطار معتدلة غير مصاحبة للبرد.',
                'soil_and_ph' => 'تربة طينية صفراء كلسية جيدة التهوية، pH 6.8 - 8.0.',
                'uses' => 'فاكهة مائدة، صناعة الزبيب اليمني الشهير، أوراق العنب للطبخ.',
                'pests_and_diseases' => 'البياض الدقيقي، العثة، وحشرة الفيلوكسيرا.',
                'harvesting_and_storage' => 'تقطف العناقيد الناضجة بعناية وتنقل في صناديق مبطنة، أو تجفف شمسياً لإنتاج الزبيب.',
                'image_url' => 'https://images.unsplash.com/photo-1537640538966-79f369143f8f?auto=format&fit=crop&w=800&q=80',
                'file_name' => 'plants/grapes.jpg',
                'care' => [
                    'watering_schedule' => 'كل 8-12 يوماً حتى العقد ثم كل أسبوع حتى مرحلة التلوين',
                    'sunlight_requirement' => 'شمس كاملة قوية لتركيز السكريات',
                    'temperature' => '15 - 32 مئوية',
                    'humidity' => '20% - 40%',
                    'fertilizing_schedule' => 'دفعة بوتاسيوم ذواب شهرياً في طور الامتلاء',
                    'pruning_guide' => 'تقليم شتوي جائر (قصير أو طويل بحسب الصنف) أثناء طور السكون',
                ],
            ],
            [
                'category' => 'فواكه',
                'common_name' => 'المانجو التيمي والقلب',
                'scientific_name' => 'Mangifera indica',
                'scientific_definition' => 'شجرة فاكهة استوائية معمرة ضخمة دائمة الخضرة، يعتبر سهل تهامة ولحج عاصمتها في الجزيرة العربية.',
                'description' => 'مانجو تهامة (التيمي، قلب الثور، السمكة، والسوداني) من أطيب الفواكه الاستوائية بنكهتها الغنية وحلاوتها العالية، وينتج بوفرة من فبراير حتى يوليو.',
                'planting_season' => 'أكتوبر - نوفمبر أو فبراير - أبريل',
                'harvest_time' => 'مارس - يوليو',
                'water_needs' => 'ري غزير ومنتظم خلال التزهير وعقد الثمار، مع الصرف الجيد',
                'fertilizer_needs' => 'أسمدة عضوية ومركبات NPK مدعمة بالزنك والبورون والحديد',
                'benefits' => 'غنية بفيتامين A وC، وألياف غذائية ممتازة للهضم والمناعة.',
                'growth_guide' => 'تزرع الشتلات المطعمة بمسافات 8×8 أو 10×10 أمتار لحجم الأشجار الضخم.',
                'growing_conditions' => 'جو حار رطب صيفاً ودافئ خالٍ من الصقيع شتاءً.',
                'soil_and_ph' => 'تربة طميية رملية عميقة جيدة الصرف خالية من الملوحة، pH 5.5 - 7.5.',
                'uses' => 'ثمار طازجة، عصائر استوائية، وتصدير تجاري نشط.',
                'pests_and_diseases' => 'ذبابة الفاكهة، لفحة الأزهار، البياض الدقيقي، وتشوه العناقيد الزهرية.',
                'harvesting_and_storage' => 'تجمع الثمار عند اكتمال النضج مع جزء من العنق لتفادي سيلان المادة الراتنجية.',
                'image_url' => 'https://images.unsplash.com/photo-1553279768-865429fa0078?auto=format&fit=crop&w=800&q=80',
                'file_name' => 'plants/mango.jpg',
                'care' => [
                    'watering_schedule' => 'كل 4-6 أيام صيفاً في أراضي تهامة الخفيفة',
                    'sunlight_requirement' => 'شمس كاملة مباشرة طوال العام',
                    'temperature' => '25 - 40 مئوية',
                    'humidity' => '50% - 80%',
                    'fertilizing_schedule' => 'دفعة بعد الحصاد ودفعة قبل التزهير ورش بورون وزنك',
                    'pruning_guide' => 'تقليم تهوية وفتح قلب الشجرة والتحكم في الارتفاع بعد جمع المحصول',
                ],
            ],
            [
                'category' => 'خضروات',
                'common_name' => 'الطماطم الحقلية والمحمية',
                'scientific_name' => 'Solanum lycopersicum',
                'scientific_definition' => 'نبات عشبي حولي من الفصيلة الباذنجانية، يزرع طوال العام في مختلف مناطق اليمن بحسب فصول المناخ.',
                'description' => 'المحصول الخضري اليومي الأكثر استهلاكاً في اليمن، يزرع في صعدة ومأرب وذمار في الصيف، وفي تهامة ولحج وأبين في الشتاء.',
                'planting_season' => 'طوال العام بحسب المنطقة والمناخ',
                'harvest_time' => '75-90 يوم من الشتل',
                'water_needs' => 'ري منتظم ومحكم بالتنقيط لتفادي أمراض الجذور وعفن الطرف الزهري',
                'fertilizer_needs' => 'برنامج تسميد متكامل (NPK + كالسيوم ومغنيسيوم)',
                'benefits' => 'مصدر استثنائي لمركب الليكوبين المضاد للأكسدة وفيتامينات C وK.',
                'growth_guide' => 'تشتل الشتلات في مصاطب بعرض متر ومسافة 40 سم بين الشتلات مع تركيب خراطيم التنقيط.',
                'growing_conditions' => 'شمس كاملة وحرارة معتدلة بين 20 و28 مئوية.',
                'soil_and_ph' => 'تربة خصبة جيدة الصرف وغنية بالمادة العضوية، pH 6.0 - 6.8.',
                'uses' => 'سلطات، طبخ يومي، معجون طماطم، وسحاوق يمني أصيل.',
                'pests_and_diseases' => 'توتا أبسلوتا (حافرة الطماطم)، اللفحة المبكرة والمتأخرة، والذبابة البيضاء.',
                'harvesting_and_storage' => 'الجني في الصباح الباكر وتعبئة الثمار في صناديق بلاستيكية مهواة.',
                'image_url' => 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=800&q=80',
                'file_name' => 'plants/tomato.jpg',
                'care' => [
                    'watering_schedule' => 'يومياً أو كل يومين بالتنقيط في الصباح الباكر',
                    'sunlight_requirement' => 'شمس كاملة (6-8 ساعات يومياً)',
                    'temperature' => '18 - 30 مئوية',
                    'humidity' => '40% - 60%',
                    'fertilizing_schedule' => 'تسميد مع مياه الري أسبوعياً ورش كالسيوم وقائي',
                    'pruning_guide' => 'إزالة السرطانات الجانبية في الأصناف غير المحدودة وتوجيه الساق الرئيسية',
                ],
            ],
            [
                'category' => 'خضروات',
                'common_name' => 'البطاطس',
                'scientific_name' => 'Solanum tuberosum',
                'scientific_definition' => 'نبات درني درناته تحت أرضية نشوية من العائلة الباذنجانية، يمثل محصولاً نقدياً وغذائياً عملاقاً في اليمن.',
                'description' => 'تعتبر محافظات ذمار وصنعاء وعمران وإب من أكبر منتجي البطاطس ذات الجودة العالية في الجزيرة العربية بفضل أراضيها البركانية الخصبة.',
                'planting_season' => 'الموسم الصيفي (مارس - أبريل) والشتوي (أغسطس - سبتمبر)',
                'harvest_time' => '90-110 يوم',
                'water_needs' => 'ري منتظم ومتقارب لتوفير رطوبة ثابتة في منطقة الدرنات',
                'fertilizer_needs' => 'فوسفور عالي في البداية وبوتاسيوم وفير أثناء صب الدرنات',
                'benefits' => 'طاقة غنية بالبوتاسيوم وفيتامين B6 والنشويات المعقدة.',
                'growth_guide' => 'تزرع التقاوي المعتمدة في خطوط وتغطى بطبقة 10 سم من التربة، مع الترديم عليها مرتين أثناء النمو.',
                'growing_conditions' => 'طقس معتدل يميل للبرودة لنمو وتضخم الدرنات.',
                'soil_and_ph' => 'تربة طميية رملية هشة ومفككة، pH 5.5 - 6.5.',
                'uses' => 'طهي منزلي، شيبس ومقليات، وتخزين تجاري للاستهلاك.',
                'pests_and_diseases' => 'اللفحة المتأخرة، فراشة درنات البطاطس، والجرب.',
                'harvesting_and_storage' => 'قطع المجموع الخضري قبل الحصاد بأسبوعين لتقوية القشرة، ثم القلع والتجفيف.',
                'image_url' => 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=800&q=80',
                'file_name' => 'plants/potato.jpg',
                'care' => [
                    'watering_schedule' => 'كل 5-7 أيام حتى اصفرار العروش ثم إيقاف الري تماماً',
                    'sunlight_requirement' => 'شمس كاملة مباشرة',
                    'temperature' => '15 - 24 مئوية',
                    'humidity' => '50% - 70%',
                    'fertilizing_schedule' => 'سلفات بوتاسيوم في ريات الصب وتجنب الإفراط في النيتروجين',
                    'pruning_guide' => 'الترديم حول السيقان لتغطية الدرنات المتكونة ومنع اخضرارها بفعل الضوء',
                ],
            ],
            [
                'category' => 'خضروات',
                'common_name' => 'البصل التهامي الأحمر',
                'scientific_name' => 'Allium cepa',
                'scientific_definition' => 'نبات بصلي حولي أو ثنائي الحول من الفصيلة النرجسية، يزرع بنجاح فائق في تهامة ومأرب وصنعاء.',
                'description' => 'البصل اليمني ممتاز جداً في قدرته التخزينية ومقاومته للتلف وصلابة قشوره، ويصدر سنوياً لأسواق الجوار.',
                'planting_season' => 'أكتوبر - ديسمبر في المناطق الدافئة',
                'harvest_time' => '120-140 يوم',
                'water_needs' => 'ري خفيف منتظم، وقطع الري نهائياً قبل الحصاد بـ 3 أسابيع',
                'fertilizer_needs' => 'تسميد عضوي أولي ونيتروجين وفوسفور وبوتاسيوم متوازن',
                'benefits' => 'مضاد حيوي طبيعي غني بالكبريت والكويرسيتين ومقوٍ لجهاز المناعة.',
                'growth_guide' => 'زراعة الشتلات على مسافات 10 سم على جانبي خطوط الري بالتنقيط.',
                'growing_conditions' => 'جو بارد معتدل في بداية النمو وحار جاف عند نضج الأبصال.',
                'soil_and_ph' => 'تربة صفراء خفيفة جيدة الصرف لا تحتفظ بالماء الزائد، pH 6.0 - 7.0.',
                'uses' => 'تتبيل الأطعمة، الاستهلاك النيء والمطبوخ، والتجفيف.',
                'pests_and_diseases' => 'تربس البصل، العفن القرمزي، والعفن الأبيض.',
                'harvesting_and_storage' => 'الحصاد عند رقاد 70% من العروش، وتترك في الحقل للتشميع ثم تخزن في مكان جاف.',
                'image_url' => 'https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?auto=format&fit=crop&w=800&q=80',
                'file_name' => 'plants/onion.jpg',
                'care' => [
                    'watering_schedule' => 'كل 6-8 أيام في الشتاء وتصويم المحصول قبل الحصاد',
                    'sunlight_requirement' => 'نهار طويل مشمس (8 ساعات على الأقل)',
                    'temperature' => '16 - 30 مئوية',
                    'humidity' => '30% - 50%',
                    'fertilizing_schedule' => 'تسميد معتدل وتوقف النيتروجين قبل شهر من الجني',
                    'pruning_guide' => 'مكافحة دقيقة للحشائش لمنع منافستها للأبصال الضحلة',
                ],
            ],
            [
                'category' => 'فواكه',
                'common_name' => 'النخيل والبلح اليمني',
                'scientific_name' => 'Phoenix dactylifera',
                'scientific_definition' => 'شجرة نخيلية دائمة الخضرة معمرة، تزدهر في حضرموت والحديدة والجوف ومأرب وشبوة.',
                'description' => 'يمتلك اليمن أصناف تمور عريقة وممتازة (مثل الخضري، السري، الجعيدي، والمناصيف)، وتعتبر شجرة الصبر والبركة في البيئات الصحراوية والساحلية.',
                'planting_season' => 'مارس - أبريل أو سبتمبر - أكتوبر (غرس الفسائل)',
                'harvest_time' => 'يوليو - أكتوبر',
                'water_needs' => 'تتحمل العطش لكنها تحتاج لري غزير دوري لإنتاج تمور ممتلئة ممتازة',
                'fertilizer_needs' => 'سماد بلدي متخمر شتاءً وأسمدة بوتاسية أثناء نمو العراجين',
                'benefits' => 'غذاء كامل وسهل الهضم غني بالمعادن والألياف والبوتاسيوم والسكريات الطبيعية.',
                'growth_guide' => 'غرس الفسائل القوية المأخوذة من أمهات جيدة بعد معالجتها ضد سوسة النخيل.',
                'growing_conditions' => 'شمس حارقة وجو جاف أثناء التمر ورطوبة أرضية متوفرة.',
                'soil_and_ph' => 'تتحمل التربة الرملية والملوحة حتى درجات عالية، pH 6.5 - 8.5.',
                'uses' => 'رطب، تمور مكنوزة، صناعة الدبس، واستخدام السعف والخشب.',
                'pests_and_diseases' => 'سوسة النخيل الحمراء، الحميرة، حلم الغبار (الغبير)، وخياس الطلع.',
                'harvesting_and_storage' => 'قص العراجين في أطوار البلح أو الرطب أو التمر، والفرز في غرف محكمة.',
                'image_url' => 'https://images.unsplash.com/photo-1549419134-93e115049b81?auto=format&fit=crop&w=800&q=80',
                'file_name' => 'plants/date_palm.jpg',
                'care' => [
                    'watering_schedule' => 'كل أسبوعين صيفاً وشهر شتاءً للأشجار الكبيرة',
                    'sunlight_requirement' => 'شمس كاملة مباشرة وشديدة',
                    'temperature' => '25 - 48 مئوية',
                    'humidity' => '20% - 40%',
                    'fertilizing_schedule' => 'تسميد عضوي عميق في الخندق الشتوي وبوتاسيوم في الربيع',
                    'pruning_guide' => 'تكريب وقص الكرب والسعف الجاف سنوياً والتلقيح اليدوي الدقيق للطلع',
                ],
            ],
            [
                'category' => 'أعشاب ونباتات طبية',
                'common_name' => 'الحلبة البلدية',
                'scientific_name' => 'Trigonella foenum-graecum',
                'scientific_definition' => 'نبات حولي بقولي ذو أزهار بيضاء صفراء، لا تكاد تخلو مائدة يمنية من منتجه في طبق السلتة والفحسة.',
                'description' => 'تزرع الحلبة في مزارع صنعاء وذمار وصعدة والبيضاء، بذورها عطرية غنية وتطحن لتصنع منها الحلبة المخفوقة الشهيرة.',
                'planting_season' => 'أكتوبر - نوفمبر',
                'harvest_time' => '90-100 يوم',
                'water_needs' => 'معتدل، ري كل 10-12 يوماً',
                'fertilizer_needs' => 'فوسفات فقط، حيث تثبت النيتروجين الجوي بنفسها كبقوليات',
                'benefits' => 'تخفض السكر في الدم، تحسن الهضم، مدرة للحليب، ومقوية للشهية والصحة العامة.',
                'growth_guide' => 'بذر البذور نثراً في أحواض مستوية، والري بهدوء لتفادي جرف البذور السطحية.',
                'growing_conditions' => 'جو بارد معتدل وشمس كاملة.',
                'soil_and_ph' => 'تربة طينية خفيفة خصبة، pH 6.0 - 7.5.',
                'uses' => 'إعداد طبق السلتة اليمني، مشروبات دافئة، واستخدامات دوائية.',
                'pests_and_diseases' => 'البياض الدقيقي، حشرات المن، والديدان القارضة.',
                'harvesting_and_storage' => 'تقلع النباتات عند اصفرار القرون وتجفف شمسياً ثم تدق وتغربل.',
                'image_url' => 'https://images.unsplash.com/photo-1599818855423-e5d761e389d3?auto=format&fit=crop&w=800&q=80',
                'file_name' => 'plants/fenugreek.jpg',
                'care' => [
                    'watering_schedule' => 'ري خفيف كل 10 أيام مع تجنب التغريق',
                    'sunlight_requirement' => 'شمس كاملة',
                    'temperature' => '12 - 25 مئوية',
                    'humidity' => '30% - 50%',
                    'fertilizing_schedule' => 'جرعة فوسفاتية عند تجهيز الأرض فقط',
                    'pruning_guide' => 'إزالة الحشائش باليد في المراحل الأولى',
                ],
            ],
            [
                'category' => 'محاصيل نقدية',
                'common_name' => 'السمسم البلدي',
                'scientific_name' => 'Sesamum indicum',
                'scientific_definition' => 'نبات زيتي حولي صيفي، تنتج منه معاصر السليط التقليدية اليمنية أجود أنواع زيت السمسم البلدي.',
                'description' => 'يزرع السمسم في تهامة ومأرب والجوف وأبين، وتعد معاصر الجمل الحجرية التقليدية جزءاً أصيلاً من التراث الزراعي اليمني لاستخراج زيت الجلجلان النقي.',
                'planting_season' => 'مايو - يوليو (الموسم الصيفي)',
                'harvest_time' => '85-100 يوم',
                'water_needs' => 'قليل ومتحمل للجفاف، يروى مرتين أو ثلاث ريات فقط',
                'fertilizer_needs' => 'سماد متوازن خفيف عند الزراعة',
                'benefits' => 'زيت صحي غني بالدهون غير المشبعة والكالسيوم ومضادات الأكسدة.',
                'growth_guide' => 'تخلط البذور الدقيقة مع الرمل لضمان التوزيع المتجانس وتبذر على خطوط.',
                'growing_conditions' => 'حرارة مرتفعة وجو مشمس وأراضٍ سهلية منبسطة.',
                'soil_and_ph' => 'تربة طميية رملية جيدة الصرف، pH 6.0 - 7.5.',
                'uses' => 'عصر زيت السمسم (السليط)، صناعة الحلويات، والمخبوزات.',
                'pests_and_diseases' => 'دودة قرون السمسم، المن، والذبول البكتيري.',
                'harvesting_and_storage' => 'الحصاد عند اصفرار النبات وقبل تفتح القرون السفلية، يربط في حزم رأسية للتجفيف.',
                'image_url' => 'https://images.unsplash.com/photo-1508061252445-5350f3ab0a55?auto=format&fit=crop&w=800&q=80',
                'file_name' => 'plants/sesame.jpg',
                'care' => [
                    'watering_schedule' => 'رية بعد الإنبات ورية عند التزهير وأخرى عند عقد القرون',
                    'sunlight_requirement' => 'شمس حارقة كاملة',
                    'temperature' => '25 - 38 مئوية',
                    'humidity' => '30% - 60%',
                    'fertilizing_schedule' => 'تسميد خفيف وتجنب زيادة النيتروجين لمنع هياج المجموع الخضري',
                    'pruning_guide' => 'خف النباتات على مسافة 15 سم بين النبات والآخر',
                ],
            ],
        ];

        foreach ($plants as $p) {
            $catId = $categoryMap[$p['category']] ?? null;

            $imagePath = ImageHelper::download($p['image_url'], $p['file_name'], $p['common_name']);

            $plant = Plant::updateOrCreate(
                ['common_name' => $p['common_name']],
                [
                    'category_id' => $catId,
                    'scientific_name' => $p['scientific_name'],
                    'scientific_definition' => $p['scientific_definition'],
                    'description' => $p['description'],
                    'benefits' => $p['benefits'],
                    'growth_guide' => $p['growth_guide'],
                    'growing_conditions' => $p['growing_conditions'],
                    'soil_and_ph' => $p['soil_and_ph'],
                    'uses' => $p['uses'],
                    'pests_and_diseases' => $p['pests_and_diseases'],
                    'harvesting_and_storage' => $p['harvesting_and_storage'],
                    'image_url' => $imagePath,
                    'planting_season' => $p['planting_season'],
                    'water_needs' => $p['water_needs'],
                    'harvest_time' => $p['harvest_time'],
                    'fertilizer_needs' => $p['fertilizer_needs'],
                ]
            );

            // Care Guide
            CareGuide::updateOrCreate(
                ['plant_id' => $plant->id],
                [
                    'watering_schedule' => $p['care']['watering_schedule'],
                    'sunlight_requirement' => $p['care']['sunlight_requirement'],
                    'temperature' => $p['care']['temperature'],
                    'humidity' => $p['care']['humidity'],
                    'management_tips' => ($p['care']['fertilizing_schedule'] ?? '').' | '.($p['care']['pruning_guide'] ?? ''),
                    'pests_and_diseases' => $p['pests_and_diseases'],
                    'harvesting_and_storage' => $p['harvesting_and_storage'],
                ]
            );

            // Mirror into CropGuide for legacy/mobile endpoints
            CropGuide::updateOrCreate(
                ['name' => $p['common_name']],
                [
                    'scientific_name' => $p['scientific_name'],
                    'category' => $p['category'],
                    'description' => $p['description'],
                    'scientific_definition' => $p['scientific_definition'],
                    'growing_conditions' => $p['growing_conditions'],
                    'soil_and_ph' => $p['soil_and_ph'],
                    'benefits' => $p['benefits'],
                    'uses' => $p['uses'],
                    'pests_and_diseases' => $p['pests_and_diseases'],
                    'harvesting_and_storage' => $p['harvesting_and_storage'],
                    'planting_season' => $p['planting_season'],
                    'water_needs' => $p['water_needs'],
                    'fertilizer_needs' => $p['fertilizer_needs'],
                    'harvest_time' => $p['harvest_time'],
                    'watering_schedule' => $p['care']['watering_schedule'],
                    'sunlight_requirement' => $p['care']['sunlight_requirement'],
                    'temperature' => $p['care']['temperature'],
                    'humidity' => $p['care']['humidity'],
                    'image_url' => $imagePath,
                ]
            );
        }
    }
}
