CREATE TABLE IF NOT EXISTS iot_devices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    device_id TEXT UNIQUE NOT NULL,
    name TEXT DEFAULT 'المستشعر المركزي',
    status TEXT DEFAULT 'online',
    temperature FLOAT DEFAULT 0,
    humidity FLOAT DEFAULT 0,
    soil_moisture FLOAT DEFAULT 0,
    water_level FLOAT DEFAULT 0,
    rain_level FLOAT DEFAULT 0,
    is_irrigation_on BOOLEAN DEFAULT false,
    auto_irrigation BOOLEAN DEFAULT false,
    auto_threshold INTEGER DEFAULT 30,
    water_consumption FLOAT DEFAULT 0,
    last_sync_at TIMESTAMPTZ DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insert the master device row
INSERT INTO iot_devices (device_id, name) 
VALUES ('ESP32-MASTER-001', 'المستشعر المركزي')
ON CONFLICT (device_id) DO NOTHING;
